name: LearningDart
version: 1.0.0
description: Learn how to program in dart.
homepage: www.myhome.com

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.15.1

dependencies:
  path: ^1.7.0
